version: 1.4.4
name: FirstPlugin
main: com.hao.firstplugin.Main
author: Hao
description: First Plugin Made
commands:
  hello:
    aliases: [hi]
    description: A command to say hello back and set full health.
  trolltoggle:
    aliases: [troll]
    description: A command to troll players.
  spawnstand:
    aliases: []
    description: A command that will spawn the stand.